plugins {
    id 'com.android.application'
}

android {
    namespace 'pl.przemysl.cloud.mobile'
    compileSdk 36

    defaultConfig {
        applicationId 'pl.przemysl.cloud.mobile'
        minSdk 29
        targetSdk 36
        versionCode 1
        versionName '1.0.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
